# networks:
#   inception:
#     name: inception

services:
  # nginx:
  #   container_name: nginx
  #   build: ./nginx
  #   ports:
  #     - "443:443"
  #   networks:
  #     - inception
  
  # wordpress:
  #   container_name: wordpress
  #   build: ./wordpress
  #   ports:
  #     - "8081:80"
  #   # depends_on:
  #   #   - db, nginx
  #   networks:
  #     - inception
  #   volumes:
  #     - ./wordpress:/var/www/html

  mariadb:
    container_name: mariadb
    build: ./mariadb
    ports:
      - "3306:3306"
    # networks:
    #   - inception
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env