services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
  
  wordpress:
    container_name: wordpress
    build: ./wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
      # - nginx
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: ./mariadb
    # depends_on:
    #   - nginx
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql   #ここはベタガキした方がいい。名前付きは権限問題に直面する。
    env_file:
      - .env

volumes:
  wordpress:
  db:

networks:
  inception:
    name: inception
    driver: bridge
  